var x_sprite;
var y_sprite;
var mytime = 0;
var mytime2 = 0;
var mycurrentime = 0;
var weight = 0;
var speed = 5;
var speedX;
var speedY;
var keyLeft;
var keyRight;
var keyUp;
var keyDown;
var keyEsc;
var keySpace;
var keyEnter;
var keyX;
var keyZ;
var huong = [];
var h;
var isAlive = true;
var realTime = 0;
var checkPlayer = true;
var player;
var itemBombs = [];
var itemShoes=[];
var countBomb=0;
var countItemSpeddGame=0;
var countkillboss=0;
var timer=0;
var bossDie=0;
var checkbossDie=0;
var isBossBomb=true;
var countPlayerHeart=5;
var myTimePlayer=0;
var myCurrentPlayer=0;
var myTimePlayerSax=0;
var myCurrentPlayerSax=0;
var layout2;
var gameOverNow=null;
var avtPlayer=null;
var tiachops=[res.TiaChopDown_png,res.TiaChopLeft_png,res.TiaChopRight_png,res.TiaChopUp_png];
var bebongs=[res.BeBongDown_png,res.BeBongLeft_png,res.BeBongRight_png,res.BeBongUp_png];
var khokhos=[res.KhoKhoDown_png,res.KhoKhoLeft_png,res.KhoKhoRight_png,res.KhoKhoDown_png];
var arrPlayer=[];
var avtplayerback=null;
var arrHighScores=[];
var highScores;
var gameWinNow=null;